%
%\documentclass[english, 11pt]{article}%!TEX root = main.Rnw
%\usepackage{haziq_article}
%\begin{document}



We consider a balanced longitudinal data set consisting of weights in kilograms of 60 cows, 30 of which were randomly assigned to treatment group A, and the remaining 30 to treatment group B. The animals were weighed 11 times over a 133-day period; the first 10 measurements for each animal were made at two-week intervals and the last measurement was made one week later. This experiment was reported by \cite{kenward1987method}, and the data set is included as part of the package \pkg{jmcm} in \proglang{R}.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{1, 1, 1}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{data}\hlstd{(cattle,} \hlkwc{package} \hlstd{=} \hlstr{"jmcm"}\hlstd{)}
\hlstd{cattle}\hlopt{$}\hlstd{id} \hlkwb{<-} \hlkwd{as.factor}\hlstd{(cattle}\hlopt{$}\hlstd{id)}  \hlcom{# convert to factors}
\hlkwd{str}\hlstd{(cattle)}
\end{alltt}
\begin{verbatim}
## 'data.frame':	660 obs. of  4 variables:
##  $ id    : Factor w/ 60 levels "1","2","3","4",..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ time  : num  0 14 28 42 56 70 84 98 112 126 ...
##  $ group : Factor w/ 2 levels "A","B": 1 1 1 1 1 1 1 1 1 1 ...
##  $ weight: int  233 224 245 258 271 287 287 287 290 293 ...
\end{verbatim}
\end{kframe}
\end{knitrout}

The response variable of interest are the \code{weight} growth curves, and the aim is to investigate whether a treatment effect is present. The usual approach to analyse a longitudinal data set such as this one is to assume that the observed growth curves are realizations of a Gaussian process. For example, \cite{kenward1987method} assumed a so-called ante-dependence structure of order $k$, which assumes an observation depends on the previous $k$ observations, but given these, is independent of any preceeding observations.

Using the I-prior, it is not necessary to assume the growth curves were drawn randomly. Instead, it suffices to assume that they lie in an appropriate function class. For this example, we assume that the function class is the FBM RKHS, i.e., we assume a smooth effect of time on weight. The growth curves form a multidimensional (or functional) response equivalent to a ``wide'' format of representing repeated measures data. In our analysis using the \pkg{iprior} package, we used the ``long'' format and thus our (unidimensional) sample size $n$ is equal to $60$ cows $\times$ $11$ repeated measurements. We also have two covariates potentially influencing growth, namely the cow subject \code{id} and also treatment \code{group}. The regression model can be thought of as
\[
  \text{\code{weight}} = f(\text{\code{id}}, \, \text{\code{group}}, \, \text{\code{time}}) + \text{error}.
\]

We assume iid errors, and in addition to a smooth effect of \code{time}, we further assume a nominal effect of both cow \code{id} and treatment \code{group} using the Pearson RKHS. In the \pkg{iprior} package, factor type objects are treated with the Pearson kernel automatically, and the only \code{model} option we need to specify is the \code{kernel = "FBM"} option for the \code{time} variable. We have opted not to estimate the Hurst coefficient in the interest of computational time, and instead left it at the default value of 0.5. Table \ref{tab:cowmodel} explains the five models we have fitted.

\begin{table}[ht]
\centering
\begin{tabular}{lp{6cm}l}
\hline
Model & Explanation & Formula                              \\
\hline
1     & Growth does not vary with treatment nor among cows                                                         & \code{weight ~ time}                 \\
\Top
2     & Growth varies among cows only                                                                              & \code{weight ~ id * time}              \\
\Top
3     & Growth varies with treatment only                                                                          & \code{weight ~ group * time}           \\
\Top
4     & Growth varies with treatment and among cows                                                                & \code{weight ~ id * time + group * time} \\
\Top
5     & Growth varies with treatment and among cows, with an interaction effect between treatment and cow & \code{weight ~ id * group * time} \\
\hline
\end{tabular}
\caption{A brief description of the five models fitted using I-priors.}
\label{tab:cowmodel}
\end{table}

The simplest model fitted was one in which the growth curves do not depend on the treatment effect or individual cows. We then added treatment effect and the cow \code{id} as covariates, separately first and then together at once. We also assumed that both of these covariates are time-varying, and hence added also the interaction between these covariates and the \code{time} variable. The final model was one in which an interaction between treatment effect and individual cows was assumed, which varied over time.

All models were first loaded into a \code{ipriorKernel} object, and then fitted using the \code{ipriorOptim} function. Compared to the EM algorithm alone, we found that the combination of direct optimization with the EM algorithm in the \code{ipriorOptim} routine fits the model about six times faster for this data set due to slow convergence of EM algorithm. Here is the code and output for fitting the first model.



\begin{knitrout}
\definecolor{shadecolor}{rgb}{1, 1, 1}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{mod1} \hlkwb{<-} \hlkwd{kernL}\hlstd{(weight} \hlopt{~} \hlstd{time,} \hlkwc{data} \hlstd{= cattle,} \hlkwc{model} \hlstd{=} \hlkwd{list}\hlstd{(}\hlkwc{kernel} \hlstd{=} \hlstr{"FBM"}\hlstd{))}
\hlstd{mod1.fit} \hlkwb{<-} \hlkwd{ipriorOptim}\hlstd{(mod1)}
\end{alltt}
\begin{verbatim}
## Iteration 0:    Log-likelihood = -29189.441 
## Iteration 1:    Log-likelihood = -4847.9320 ........
## Iteration 2:    Log-likelihood = -3207.6196 .......
## Iteration 3:    Log-likelihood = -2991.1667 .......
## EM NOT CONVERGED!
## 
## Now switching to optim...
## 
## final  value 2789.684969 
## converged
## 
## Preparing iprior output... DONE.
\end{verbatim}
\end{kframe}
\end{knitrout}

The \code{ipriorOptim} routine (see Section \ref{sec:iprioroptim} for details) performs three EM iterations from a random starting value of the parameters. After the initial EM steps, a direct optimization is carried out using \proglang{R}'s built-in optimizer \code{optim()}. The user has several \code{control} options to choose from, such as specifying the number of initial EM steps to be performed.

\newcolumntype{R}[1]{>{\raggedleft\arraybackslash}p{#1}}
\begin{table}[ht]
\centering
\begin{tabular}{lp{4.9cm}R{2.3cm}R{2.3cm}R{2.5cm}}
\hline
{\small Model}
& {\small{Formula \newline (}\code{weight ~ ...}{)}}
& {\small{Log-likelihood}}
& {\small{Error standard  deviation}}
& {\small{Number of $\lambda$ parameters}}  \\
\hline
1     & \code{time}                   & -2789.63 & 16.27 & 1 \\
2     & \code{id * time}                & -2789.82 & 16.3 & 2 \\
3     & \code{group * time}             & -2295.16 & 3.68 & 2 \\
4     & \code{id * time + group * time}   & -2270.85 & 3.39 & 3 \\
5     & \code{id * group * time}          & -2250.88 & 3.77 & 3 \\
\hline
\end{tabular}
\caption{Summary of the five I-prior models fitted to the cow data set.}
\label{tab:cowresults}
\end{table}

The results of the model fit are summarised in Table \ref{tab:cowresults}. We can test for a treatment effect by testing Model 4 against the alternative that Model 2 is true. The log-likelihood ratio test statistic is $D = -2(-2789.82 - (-2270.85)) = 1037.94$ which has an asymptotic chi-squared distribution with $3 - 2 = 1$ degree of freedom. The $p$-value for this likelihood ratio test is less than $10^{-6}$, so we conclude that Model 4 is significantly better than Model 2.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{1, 1, 1}\color{fgcolor}\begin{figure}[H]

{\centering \includegraphics[width=14.25cm,height=9.5cm]{figure/ipriorplot-1} 

}

\caption[A plot of the I-prior fitted regression curves from Model 5]{A plot of the I-prior fitted regression curves from Model 5. In this model, growth curves differ among cows and by treatment effect (with an interaction between cows and treatment effect), thus producing these 60 individual lines, one for each cow. The points are labelled with the cow \code{id} and treatment \code{group} it was assigned to.}\label{fig:ipriorplot}
\end{figure}


\end{knitrout}

We can next investigate whether the treatment effect differs among cows by comparing Model 5 against Model 4. As these models have the same number of parameters, we can simply choose the one with the higher likelihood, which is Model 5. We conclude that treatment does indeed have an effect on growth, and that the treatment effect differs among cows. We can use the \code{plot} function to plot the fitted regression curves onto the cow data set. This is shown in Figure \ref{fig:ipriorplot}.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% REFERENCES %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%\nocite{*}
%\bibliographystyle{apalike}
%\bibliography{haziq}
%\end{document}
